version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: devroots-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 111%k!HRgmu@4T
      POSTGRES_DB: mydatabase
    ports:
      - "4005:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
