/* eslint-disable no-unused-vars, @typescript-eslint/no-unused-vars */
export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_ID_FORMAT = 'INVALID_ID_FORMAT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  TOOLS_NOT_FOUND = 'TOOLS_NOT_FOUND',
  TOOL_NOT_FOUND = 'TOOL_NOT_FOUND',
  ACCESS_DENIED_NO_TOKEN = 'ACCESS_DENIED_NO_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
