#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test
npm run lint 
npm run format:check
if [ $? -ne 0 ]; then
  echo "Tests or linting failed. Please fix the issues before committing."
  exit 1
fi
echo "All tests and linting passed. Proceeding with commit."